POST http://localhost:8080/odata/v4/ManageMaterials/Materials HTTP/1.1
Content-Type: application/json

{
    "ID": "5e69a718-d86b-4461-8953-0edadcd87960", 
    "name": "Test1", 
    "descr": "first test"
}

###

GET http://localhost:8080/odata/v4/ManageMaterials/Materials HTTP/1.1

###

POST http://localhost:8080/odata/v4/ManageShipments/Shipments HTTP/1.1
Content-Type: application/json

{
    "fromPlant": "1000", 
    "fromStorage": "0004",
    "toPlant": "1000", 
    "toStorage": "0004",
    "status": "1",
    "notes":[]
}

###

GET http://localhost:8080/odata/v4/ManageShipments/Shipments HTTP/1.1